[build]
  publish = "public"

[context.deploy-preview]
  command = "bash .github/scripts/build-multi-version.sh $DEPLOY_PRIME_URL"

# Redirects für versionierte Pfade
[[redirects]]
  from = "/dev/*"
  to = "/dev/:splat"
  status = 200

[[redirects]]
  from = "/legacy/*"
  to = "/legacy/:splat"
  status = 200

[[redirects]]
  from = "/v*/*"
  to = "/v:version/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
