[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "23.11.0"
  NPM_VERSION = "10.9.2"


[context.production]
  command = "netlify_multi_version_build.sh"

[context.deploy-preview]
  command = "netlify_multi_version_build.sh"

[context.branch-deploy]
  command = "netlify_multi_version_build.sh"

[context.next]
  command = "npm run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://doks.netlify.app/"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "yandex"
    ]

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
