[build]
  publish = "public"

#[context.deploy-preview]
#  command = "./netlify_multi_version_build.sh"

# Redirects für versionierte Pfade
[[redirects]]
  from = "/dev/*"
  to = "/dev/:splat"
  status = 200

[[redirects]]
  from = "/legacy/*"
  to = "/legacy/:splat"
  status = 200

[[redirects]]
  from = "/v*/*"
  to = "/v:version/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200